---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csr-approver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csr-approver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csr-approver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "csr-approver.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "csr-approver.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            {{- if gt (int .Values.replicaCount) 1 }}
            - --leader-elect=true
            - --leader-election-namespace={{ .Release.Namespace }}
            - --leader-election-lease-name={{ include "csr-approver.fullname" . }}
            {{- end }}
            {{- range $rule := .Values.approvalRules }}
            - --approval-rule=signerName={{ $rule.signerName }}{{ with $rule.username }},username={{ . }}{{ end }}{{ with $rule.machineValidation }},machineValidation={{ . }}{{ end }}
            {{- end }}
            - --machine-namespace={{ .Values.machineNamespace }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
