{{- if gt (int .Values.replicaCount) 1 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "csr-approver.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
{{- end }}
{{- $machineRole := false }}
{{- range .Values.approvalRules }}
{{- if eq .machineValidation "required" }}
{{- $machineRole = true }}
{{- end }}
{{- end }}
{{- if $machineRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "csr-approver.fullname" . }}-machines
  namespace: {{ .Values.machineNamespace }}
rules:
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - machines
    verbs:
      - get
{{- end }}
