replicaCount: 1

# Each approvalRules requires signerName. username is optional.
# You need at least one rule so the application works
approvalRules:
  - signerName: kubernetes.io/kube-apiserver-client-kubelet
    username: system:serviceaccount:openshift-machine-config-operator:node-bootstrapper
  - signerName: kubernetes.io/kubelet-serving

image:
  repository: ghcr.io/mithweth/csr-approver
  pullPolicy: IfNotPresent
  pullSecretName: ""
  tag: ""

fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
