replicaCount: 3

# Each approval rule requires signerName.
# username, machineValidation, and commonNameValidation are optional.
# machineValidation checks for a Cluster API Machine whose name matches
# the common name contained in the CSR.
# commonNameValidation requires the CSR username to match the common name
# contained in the CSR (system:node:<name>).
# At least one rule is required for the application to approve CSRs.
approvalRules:
  - signerName: kubernetes.io/kube-apiserver-client-kubelet
    username: system:serviceaccount:openshift-machine-config-operator:node-bootstrapper
    # machineValidation: required  # required, disabled
    # commonNameValidation: required  # required, disabled
  - signerName: kubernetes.io/kubelet-serving

# Namespace containing the Cluster API Machines.
machineNamespace: kube-system

image:
  repository: ghcr.io/mithweth/csr-approver
  pullPolicy: IfNotPresent
  pullSecretName: ""
  tag: ""

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    labels: {}
    annotations: {}
    interval: 30s

service:
  type: ClusterIP
  labels: {}
  annotations: {}

fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
