replicaCount: 3

# Each approvalRules requires signerName. username and machineValidation are optional.
# machineValidation check a cluster-API Machine whose name matchs CSR common name.
# You need at least one rule so the application works
approvalRules:
  - signerName: kubernetes.io/kube-apiserver-client-kubelet
    username: system:serviceaccount:openshift-machine-config-operator:node-bootstrapper
    # machineValidation: required  # required, disabled
  - signerName: kubernetes.io/kubelet-serving

# The namespace where cluster-API Machines are located
machineNamespace: kube-system

image:
  repository: ghcr.io/mithweth/csr-approver
  pullPolicy: IfNotPresent
  pullSecretName: ""
  tag: ""

metrics:
  enabled: false

service:
  type: ClusterIP
  labels: {}
  annotations: {}

fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
