name: Test and lint

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        shell: bash
        run: |
          go vet ./...
          go test ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
